/**
 * get person fields
 */

/*
{
  "success": true,
  "data": [
    {
      "id": 9038,
      "key": "name",
      "name": "Name",
      "order_nr": 1,
      "picklist_data": null,
      "field_type": "varchar",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": true,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "use_field": "id",
      "link": "/person/",
      "mandatory_flag": true
    },
    {
      "id": 9039,
      "key": "label",
      "name": "Label",
      "order_nr": 2,
      "field_type": "enum",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": true,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "options": [
        {
          "color": "green",
          "label": "Customer",
          "id": 1
        },
        {
          "color": "red",
          "label": "Hot lead",
          "id": 2
        },
        {
          "color": "yellow",
          "label": "Warm lead",
          "id": 3
        },
        {
          "color": "blue",
          "label": "Cold lead",
          "id": 4
        }
      ],
      "mandatory_flag": false
    },
    {
      "id": 9061,
      "key": "first_name",
      "name": "First name",
      "order_nr": 2,
      "picklist_data": null,
      "field_type": "varchar",
      "add_time": "2020-03-12 02:27:28",
      "update_time": "2020-03-12 02:27:28",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": false
    },
    {
      "id": 9062,
      "key": "last_name",
      "name": "Last name",
      "order_nr": 2,
      "picklist_data": null,
      "field_type": "varchar",
      "add_time": "2020-03-12 02:27:28",
      "update_time": "2020-03-12 02:27:28",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": false
    },
    {
      "id": 9040,
      "key": "phone",
      "name": "Phone",
      "order_nr": 3,
      "picklist_data": null,
      "field_type": "phone",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": true,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": false
    },
    {
      "id": 9041,
      "key": "email",
      "name": "Email",
      "order_nr": 4,
      "picklist_data": null,
      "field_type": "varchar",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": true,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": false
    },
    {
      "id": 9042,
      "key": "add_time",
      "name": "Person created",
      "order_nr": 5,
      "picklist_data": null,
      "field_type": "date",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9043,
      "key": "update_time",
      "name": "Update time",
      "order_nr": 6,
      "picklist_data": null,
      "field_type": "date",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9044,
      "key": "org_id",
      "name": "Organization",
      "order_nr": 7,
      "picklist_data": null,
      "field_type": "org",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": true,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "use_field": "org_id",
      "display_field": "org_name",
      "link": "/organization/",
      "autocomplete": "org_autocomplete",
      "mandatory_flag": false
    },
    {
      "id": 9045,
      "key": "owner_id",
      "name": "Owner",
      "order_nr": 8,
      "picklist_data": null,
      "field_type": "user",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": true,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "use_field": "owner_id",
      "display_field": "owner_name",
      "mandatory_flag": true
    },
    {
      "id": 9046,
      "key": "open_deals_count",
      "name": "Open deals",
      "order_nr": 9,
      "picklist_data": null,
      "field_type": "double",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9047,
      "key": "visible_to",
      "name": "Visible to",
      "order_nr": 10,
      "field_type": "visible_to",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": true,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": true,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "options": [
        {
          "id": 1,
          "label": "owner only"
        },
        {
          "id": 3,
          "label": "owner's visibility group"
        },
        {
          "id": 5,
          "label": "owner's visibility group and groups below"
        },
        {
          "id": 7,
          "label": "entire company"
        }
      ],
      "mandatory_flag": true
    },
    {
      "id": 9048,
      "key": "next_activity_date",
      "name": "Next activity date",
      "order_nr": 11,
      "picklist_data": null,
      "field_type": "date",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9049,
      "key": "last_activity_date",
      "name": "Last activity date",
      "order_nr": 12,
      "picklist_data": null,
      "field_type": "date",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9050,
      "key": "id",
      "name": "ID",
      "order_nr": 13,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9051,
      "key": "won_deals_count",
      "name": "Won deals",
      "order_nr": 14,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9052,
      "key": "lost_deals_count",
      "name": "Lost deals",
      "order_nr": 15,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9053,
      "key": "closed_deals_count",
      "name": "Closed deals",
      "order_nr": 16,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9054,
      "key": "activities_count",
      "name": "Total activities",
      "order_nr": 17,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9055,
      "key": "done_activities_count",
      "name": "Done activities",
      "order_nr": 18,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9056,
      "key": "undone_activities_count",
      "name": "Activities to do",
      "order_nr": 19,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9057,
      "key": "email_messages_count",
      "name": "Email messages count",
      "order_nr": 20,
      "picklist_data": null,
      "field_type": "int",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9058,
      "key": "picture_id",
      "name": "Profile picture",
      "order_nr": 21,
      "picklist_data": null,
      "field_type": "picture",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9059,
      "key": "last_incoming_mail_time",
      "name": "Last email received",
      "order_nr": 22,
      "picklist_data": null,
      "field_type": "date",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    },
    {
      "id": 9060,
      "key": "last_outgoing_mail_time",
      "name": "Last email sent",
      "order_nr": 23,
      "picklist_data": null,
      "field_type": "date",
      "add_time": "2020-03-11 22:53:32",
      "update_time": "2020-03-11 22:53:32",
      "last_updated_by_user_id": null,
      "active_flag": true,
      "edit_flag": false,
      "index_visible_flag": true,
      "details_visible_flag": false,
      "add_visible_flag": false,
      "important_flag": false,
      "bulk_edit_allowed": false,
      "searchable_flag": false,
      "filtering_allowed": true,
      "sortable_flag": true,
      "mandatory_flag": true
    }
  ],
  "additional_data": {
    "pagination": {
      "start": 0,
      "limit": 100,
      "more_items_in_collection": false
    }
  }
}
*/

import { getSessionToken } from './common'
import {
  host,
  notify
} from 'ringcentral-embeddable-extension-common/src/common/helpers'
import fetch from 'ringcentral-embeddable-extension-common/src/common/fetch'

async function getPersonFields () {
  const token = getSessionToken()
  const url = `${host}/api/v1/personFields?session_token=${token}&strict_mode=true`
  const res = await fetch.get(url)
  if (res && res.data && res.data.length) {
    return res.data
  } else {
    notify('Can not sync log to deal, due to fetch person fields failed', 10000)
  }
}

export default async () => {
  const arr = await getPersonFields()
  const nameField = arr.find(a => a.key === 'id')
  if (nameField && nameField.id) {
    return nameField.id
  } else {
    notify('Can not sync log to deal, due to no id person field', 10000)
  }
}
